version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:5000/api
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules

  server:
    build: .
    working_dir: /app/server
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules

volumes:
  node_modules:
  server_node_modules: